const assert = require('node:assert/strict');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({headless:true, executablePath:process.env.BROWSER_PATH || undefined, args:['--no-sandbox']});
  const page = await browser.newPage();
  const errors=[];
  if(process.env.HIGO_STATIC_DIR)await page.route('**/app.js',route=>route.fulfill({path:process.env.HIGO_STATIC_DIR+'/app.js',contentType:'application/javascript'})); page.on('pageerror', e=>errors.push(e.message));
  await page.goto(process.env.HIGO_BASE_URL || 'http://localhost:8080');
  await page.locator('#account').click();
  await page.locator('[name=phone]').fill('139'+String(Date.now()).slice(-8));
  await page.locator('#send').click();
  await page.waitForFunction(()=>document.querySelector('[name=code]').value.length===6);
  await page.locator('#login button.primary').click();
  await page.waitForFunction(()=>!document.querySelector('#modal').open);
  const name='浏览器咖啡 '+Date.now();
  await page.locator('#create-shop').click();
  await page.locator('#shop-form [name=name]').fill(name);
  await page.locator('#shop-form [name=category]').fill('咖啡');
  await page.locator('#shop-form [name=address]').fill('广州测试路');
  await page.locator('#shop-form button.primary').click();
  await page.getByRole('heading',{name,exact:true}).waitFor();
  await page.locator('article').filter({hasText:name}).getByRole('button').click();
  await page.locator('#add-voucher').click();
  await page.locator('#voucher-form [name=title]').fill('咖啡优惠');
  await page.locator('[name=price]').fill('9.90');
  await page.locator('[name=stock]').fill('3');
  await page.locator('[name=beginAt]').fill('2020-01-01T00:00');
  await page.locator('[name=endAt]').fill('2099-01-01T00:00');
  await page.locator('#voucher-form button.primary').click();
  await page.locator('[data-buy]').click();
  await page.locator('[data-cancel]').first().waitFor({timeout:30000});
  await page.locator('[data-cancel]').first().click();
  await page.getByText('已取消',{exact:true}).first().waitFor();
  await page.locator('[data-view=blogs]').click();
  await page.locator('#publish').click();
  const title='浏览器笔记 '+Date.now();
  await page.locator('#publish-form [name=title]').fill(title);
  await page.locator('#publish-form [name=content]').fill('测试发布、点赞和评论');
  await page.locator('#publish-form button.primary').click();
  await page.getByRole('heading',{name:title,exact:true}).waitFor();
  await page.locator('article').filter({hasText:title}).getByRole('button').click();
  await page.locator('#like').click();
  await page.getByRole('button',{name:/已喜欢/}).waitFor();
  await page.locator('#comment [name=content]').fill('浏览器评论');
  await page.locator('#comment button').click();
  await page.getByText('浏览器评论',{exact:true}).waitFor();
  await page.locator('.close').click();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile overflow');
  assert.deepEqual(errors,[]);
  console.log('PASS browser: login, shop, voucher, purchase, cancellation, blog, like, comment, mobile');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
